name: "validate files"
on: push
jobs:
   validate-file:
      runs-on: ubuntu-latest
      steps:
        - name: get-repo-code
          uses: actions/checkout@v3
       
        - name: validate html file
          run: test -f index.html

        - name: validate js file
          run: test -f index.js

